# Noteworthy differences

Coming from Python, MATLAB or R, how does the experience translate to Julia? Note, also see https://docs.julialang.org/en/v1/manual/noteworthy-differences for a complete overview. Please keep the manual next https://docs.julialang.org/en/v1/manual to this course and try to use the ? help function in the REPL prompt.

## Not object oriented
Julia is not (really) objected oriented, functions don't belong to a single object (or type). Hence, the syntax is often `f(x)` and not `x.f()`. The dot notation is reserved for accessing properties (or fields) of the type.

In [21]:
A = (1,2,3)
length(A)
A.length

LoadError: type Tuple has no field length

## Difference between single and double quotes
There's a difference between `'` and `"` quotes in Julia, whereas in Python they can both be used for strings. In Julia the single quote is used for characters.

In [22]:
println(typeof('a'))
println(typeof("bb"))
println("""a string with odd " characters '... """)
'tryout'

Char
String
a string with odd " characters '... 


LoadError: syntax: character literal contains multiple characters

## Built in Array support
In Python you need numpy to have arrays and their related operations. In Julia its built-in:

In [23]:
# Vector of [1,1,1,1,1]
ones(5)

# Random two dimensional matrix
nine = rand(3,3)

3×3 Matrix{Float64}:
 0.741954  0.22644   0.12945
 0.386625  0.183048  0.70617
 0.254794  0.245816  0.309151

Note however that the order of columns and rows is different than what you're used to. Multidimensional arrays in Julia are stored in column-major order:

In [24]:
x = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [25]:
x[:]

4-element Vector{Int64}:
 1
 3
 2
 4

## Missing support
Whereas in Python you would use the numpy masking function, Julia has a built-in Missing type for this. It corresponds to the `NULL` from SQL or `NA` in R. It propagates through the use of normal math functions. There's also `nothing`, like Pythons None.

In [26]:
A = [1, missing]

2-element Vector{Union{Missing, Int64}}:
 1
  missing

In [27]:
A .* 2

2-element Vector{Union{Missing, Int64}}:
 2
  missing

In [28]:
collect(skipmissing(A))

1-element Vector{Int64}:
 1

## Usage of `end` statement
In Python the loop is ended by indentation:

```python
for x in collection:
    something()

# end of loop
```

While in Julia, you need to explicitly end the loop. The same goes for `function`s, `while`s, `if`s and `else`s and similar constructs:

In [29]:
function square(number::Int)
    number^2
end

for x in 1:10
    square(x)
end

if 1 > 10
    println("What?!")
else
    @info "This seems a sensible result"
end

[ Info: This seems a sensible result


Note that you also don't need the `:` character from Python.

## Indexing
Depending on which language you come from, this can be odd, Julia uses one based indexing, just like Fortran. But unlike C and C-like languages such as Python. However, there are options to override this and have custom indexing, not only 0 based, but also custom loops etc.

In [30]:
a = [1,2,3]
println(a[1])
println(a[end])
println(a[1:2])
println(a[1:3])
println(a[1:end])

b = rand(3,3)
println(b[1, :])  # 1 column
println(b[:, 1])  # 1 row

a[0]  # BoundsError

1
3
[1, 2]
[1, 2, 3]
[1, 2, 3]
[0.3434547775575394, 0.5801117588861286, 0.8934566009617863]
[0.3434547775575394, 0.956669384667573, 0.5138351219980384]


LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [0]

Indexing with logic is supported, although the size of these arrays must match (unlike R).

In [31]:
@show a[a .> 1]
@show a[[true, true, false]]

a[[true]]  # errors

a[a .> 1] = [2, 3]
a[[true, true, false]] = [1, 2]


LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [1-element Vector{Bool}]

Although it would more Julian to work with predicates, and maybe operate in place (reducing allocatings by mutating the array):

In [32]:
@info filter(x -> x>1, a)
@info a
filter!(x -> x>1, a)  # ! indicates a mutating function
a

[ Info: [2, 3]
[ Info: [1, 2, 3]


2-element Vector{Int64}:
 2
 3

## Exercises
We give a few problems here to try out, in a few minutes we'll provide our answers to them. Note that you could share them using [repl.it](repl.it) and generating a link there. In that way we can help you with your problems.

---
Try to generate a few Arrays, either with `rand`, `range` or typed out and add/substract these two arrays. You can also `fill!` them. What does the `!` indicate in that function?


In [33]:
range

range (generic function with 4 methods)

---
Use `hcat` or `vcat` to concatenate these two arrays and if that fails, try to understand why. You can get the size or dimensions of an Array with `length` and `ndim`. See https://docs.julialang.org/en/v1/manual/arrays/ for an overview.

---
Try to slice any of the previously made arrays and get one value out of there. Can you also assign a single value to a specific point in your array? What happens if you put in an Integer instead in an Array of floats? What happens if you compare (`==`) your two Arrays? And what happens if you do `.==`?

---
Let's try to apply some common algebra functions to your arrays. Can you use `'` (transpose)? Or use the `dot` function. Maybe the `inv` of your Matrix? See https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Linear-Algebra-1 for an overview.